export const SET_USER = 'SET_USER';
export const SET_TOKEN_ID = 'SET_TOKEN_ID';
export const SIGN_OUT = 'SIGN_OUT';
export const START_SIGN_IN = 'START_SIGN_IN';
export const START_SIGN_UP = 'START_SIGN_UP';
export const SET_FRIEND_FROM_CURRENT_INVITE = 'SET_FRIEND_FROM_CURRENT_INVITE';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

